version: "3.8"
services:
  backend:
    container_name: WitPaKul_Backend
    build: .
    image: backend
    volumes:
      - ./pictures:/pictures
networks:
  default:
    external:
      name: witpakul_network